// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_chat_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_chat_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_chat_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_chat_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_chat_2eproto;
namespace chat {
class ChatPacket;
struct ChatPacketDefaultTypeInternal;
extern ChatPacketDefaultTypeInternal _ChatPacket_default_instance_;
}  // namespace chat
PROTOBUF_NAMESPACE_OPEN
template<> ::chat::ChatPacket* Arena::CreateMaybeMessage<::chat::ChatPacket>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace chat {

enum ChatPacket_Type : int {
  ChatPacket_Type_UNKNOWN = 0,
  ChatPacket_Type_TEXT = 1,
  ChatPacket_Type_PRIVATE = 2,
  ChatPacket_Type_GROUP = 3,
  ChatPacket_Type_FILE = 4,
  ChatPacket_Type_LOGIN = 5,
  ChatPacket_Type_REGISTER = 6,
  ChatPacket_Type_SYSTEM = 7,
  ChatPacket_Type_HEARTBEAT = 8,
  ChatPacket_Type_ChatPacket_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ChatPacket_Type_ChatPacket_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ChatPacket_Type_IsValid(int value);
constexpr ChatPacket_Type ChatPacket_Type_Type_MIN = ChatPacket_Type_UNKNOWN;
constexpr ChatPacket_Type ChatPacket_Type_Type_MAX = ChatPacket_Type_HEARTBEAT;
constexpr int ChatPacket_Type_Type_ARRAYSIZE = ChatPacket_Type_Type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ChatPacket_Type_descriptor();
template<typename T>
inline const std::string& ChatPacket_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ChatPacket_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ChatPacket_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ChatPacket_Type_descriptor(), enum_t_value);
}
inline bool ChatPacket_Type_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ChatPacket_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ChatPacket_Type>(
    ChatPacket_Type_descriptor(), name, value);
}
// ===================================================================

class ChatPacket final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat.ChatPacket) */ {
 public:
  inline ChatPacket() : ChatPacket(nullptr) {}
  ~ChatPacket() override;
  explicit PROTOBUF_CONSTEXPR ChatPacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChatPacket(const ChatPacket& from);
  ChatPacket(ChatPacket&& from) noexcept
    : ChatPacket() {
    *this = ::std::move(from);
  }

  inline ChatPacket& operator=(const ChatPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatPacket& operator=(ChatPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChatPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChatPacket* internal_default_instance() {
    return reinterpret_cast<const ChatPacket*>(
               &_ChatPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ChatPacket& a, ChatPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(ChatPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatPacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChatPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChatPacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChatPacket& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChatPacket& from) {
    ChatPacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChatPacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat.ChatPacket";
  }
  protected:
  explicit ChatPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ChatPacket_Type Type;
  static constexpr Type UNKNOWN =
    ChatPacket_Type_UNKNOWN;
  static constexpr Type TEXT =
    ChatPacket_Type_TEXT;
  static constexpr Type PRIVATE =
    ChatPacket_Type_PRIVATE;
  static constexpr Type GROUP =
    ChatPacket_Type_GROUP;
  static constexpr Type FILE =
    ChatPacket_Type_FILE;
  static constexpr Type LOGIN =
    ChatPacket_Type_LOGIN;
  static constexpr Type REGISTER =
    ChatPacket_Type_REGISTER;
  static constexpr Type SYSTEM =
    ChatPacket_Type_SYSTEM;
  static constexpr Type HEARTBEAT =
    ChatPacket_Type_HEARTBEAT;
  static inline bool Type_IsValid(int value) {
    return ChatPacket_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    ChatPacket_Type_Type_MIN;
  static constexpr Type Type_MAX =
    ChatPacket_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    ChatPacket_Type_Type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Type_descriptor() {
    return ChatPacket_Type_descriptor();
  }
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return ChatPacket_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Type* value) {
    return ChatPacket_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kTextFieldNumber = 2,
    kUsernameFieldNumber = 3,
    kReceiverFieldNumber = 4,
    kGroupIdFieldNumber = 5,
    kFileIdFieldNumber = 6,
    kPayloadFieldNumber = 8,
    kFilenameFieldNumber = 10,
    kPasswordFieldNumber = 11,
    kMessageIdFieldNumber = 12,
    kStatusMessageFieldNumber = 15,
    kExtraFieldNumber = 16,
    kOffsetFieldNumber = 7,
    kTypeFieldNumber = 1,
    kStatusFieldNumber = 14,
    kFileSizeFieldNumber = 9,
    kTimestampFieldNumber = 13,
  };
  // string text = 2;
  void clear_text();
  const std::string& text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_text();
  PROTOBUF_NODISCARD std::string* release_text();
  void set_allocated_text(std::string* text);
  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(const std::string& value);
  std::string* _internal_mutable_text();
  public:

  // string username = 3;
  void clear_username();
  const std::string& username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* username);
  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(const std::string& value);
  std::string* _internal_mutable_username();
  public:

  // string receiver = 4;
  void clear_receiver();
  const std::string& receiver() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_receiver(ArgT0&& arg0, ArgT... args);
  std::string* mutable_receiver();
  PROTOBUF_NODISCARD std::string* release_receiver();
  void set_allocated_receiver(std::string* receiver);
  private:
  const std::string& _internal_receiver() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_receiver(const std::string& value);
  std::string* _internal_mutable_receiver();
  public:

  // string group_id = 5;
  void clear_group_id();
  const std::string& group_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_group_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_group_id();
  PROTOBUF_NODISCARD std::string* release_group_id();
  void set_allocated_group_id(std::string* group_id);
  private:
  const std::string& _internal_group_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_group_id(const std::string& value);
  std::string* _internal_mutable_group_id();
  public:

  // string file_id = 6;
  void clear_file_id();
  const std::string& file_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_file_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_file_id();
  PROTOBUF_NODISCARD std::string* release_file_id();
  void set_allocated_file_id(std::string* file_id);
  private:
  const std::string& _internal_file_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_id(const std::string& value);
  std::string* _internal_mutable_file_id();
  public:

  // bytes payload = 8;
  void clear_payload();
  const std::string& payload() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_payload(ArgT0&& arg0, ArgT... args);
  std::string* mutable_payload();
  PROTOBUF_NODISCARD std::string* release_payload();
  void set_allocated_payload(std::string* payload);
  private:
  const std::string& _internal_payload() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_payload(const std::string& value);
  std::string* _internal_mutable_payload();
  public:

  // string filename = 10;
  void clear_filename();
  const std::string& filename() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_filename(ArgT0&& arg0, ArgT... args);
  std::string* mutable_filename();
  PROTOBUF_NODISCARD std::string* release_filename();
  void set_allocated_filename(std::string* filename);
  private:
  const std::string& _internal_filename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filename(const std::string& value);
  std::string* _internal_mutable_filename();
  public:

  // string password = 11;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // string message_id = 12;
  void clear_message_id();
  const std::string& message_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message_id();
  PROTOBUF_NODISCARD std::string* release_message_id();
  void set_allocated_message_id(std::string* message_id);
  private:
  const std::string& _internal_message_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message_id(const std::string& value);
  std::string* _internal_mutable_message_id();
  public:

  // string status_message = 15;
  void clear_status_message();
  const std::string& status_message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_status_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_status_message();
  PROTOBUF_NODISCARD std::string* release_status_message();
  void set_allocated_status_message(std::string* status_message);
  private:
  const std::string& _internal_status_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_status_message(const std::string& value);
  std::string* _internal_mutable_status_message();
  public:

  // string extra = 16;
  void clear_extra();
  const std::string& extra() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_extra(ArgT0&& arg0, ArgT... args);
  std::string* mutable_extra();
  PROTOBUF_NODISCARD std::string* release_extra();
  void set_allocated_extra(std::string* extra);
  private:
  const std::string& _internal_extra() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_extra(const std::string& value);
  std::string* _internal_mutable_extra();
  public:

  // uint64 offset = 7;
  void clear_offset();
  uint64_t offset() const;
  void set_offset(uint64_t value);
  private:
  uint64_t _internal_offset() const;
  void _internal_set_offset(uint64_t value);
  public:

  // .chat.ChatPacket.Type type = 1;
  void clear_type();
  ::chat::ChatPacket_Type type() const;
  void set_type(::chat::ChatPacket_Type value);
  private:
  ::chat::ChatPacket_Type _internal_type() const;
  void _internal_set_type(::chat::ChatPacket_Type value);
  public:

  // int32 status = 14;
  void clear_status();
  int32_t status() const;
  void set_status(int32_t value);
  private:
  int32_t _internal_status() const;
  void _internal_set_status(int32_t value);
  public:

  // uint64 file_size = 9;
  void clear_file_size();
  uint64_t file_size() const;
  void set_file_size(uint64_t value);
  private:
  uint64_t _internal_file_size() const;
  void _internal_set_file_size(uint64_t value);
  public:

  // int64 timestamp = 13;
  void clear_timestamp();
  int64_t timestamp() const;
  void set_timestamp(int64_t value);
  private:
  int64_t _internal_timestamp() const;
  void _internal_set_timestamp(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:chat.ChatPacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr receiver_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr group_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr file_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr payload_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filename_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_message_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr extra_;
    uint64_t offset_;
    int type_;
    int32_t status_;
    uint64_t file_size_;
    int64_t timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ChatPacket

// .chat.ChatPacket.Type type = 1;
inline void ChatPacket::clear_type() {
  _impl_.type_ = 0;
}
inline ::chat::ChatPacket_Type ChatPacket::_internal_type() const {
  return static_cast< ::chat::ChatPacket_Type >(_impl_.type_);
}
inline ::chat::ChatPacket_Type ChatPacket::type() const {
  // @@protoc_insertion_point(field_get:chat.ChatPacket.type)
  return _internal_type();
}
inline void ChatPacket::_internal_set_type(::chat::ChatPacket_Type value) {
  
  _impl_.type_ = value;
}
inline void ChatPacket::set_type(::chat::ChatPacket_Type value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:chat.ChatPacket.type)
}

// string text = 2;
inline void ChatPacket::clear_text() {
  _impl_.text_.ClearToEmpty();
}
inline const std::string& ChatPacket::text() const {
  // @@protoc_insertion_point(field_get:chat.ChatPacket.text)
  return _internal_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatPacket::set_text(ArgT0&& arg0, ArgT... args) {
 
 _impl_.text_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.ChatPacket.text)
}
inline std::string* ChatPacket::mutable_text() {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:chat.ChatPacket.text)
  return _s;
}
inline const std::string& ChatPacket::_internal_text() const {
  return _impl_.text_.Get();
}
inline void ChatPacket::_internal_set_text(const std::string& value) {
  
  _impl_.text_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatPacket::_internal_mutable_text() {
  
  return _impl_.text_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatPacket::release_text() {
  // @@protoc_insertion_point(field_release:chat.ChatPacket.text)
  return _impl_.text_.Release();
}
inline void ChatPacket::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  _impl_.text_.SetAllocated(text, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.ChatPacket.text)
}

// string username = 3;
inline void ChatPacket::clear_username() {
  _impl_.username_.ClearToEmpty();
}
inline const std::string& ChatPacket::username() const {
  // @@protoc_insertion_point(field_get:chat.ChatPacket.username)
  return _internal_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatPacket::set_username(ArgT0&& arg0, ArgT... args) {
 
 _impl_.username_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.ChatPacket.username)
}
inline std::string* ChatPacket::mutable_username() {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:chat.ChatPacket.username)
  return _s;
}
inline const std::string& ChatPacket::_internal_username() const {
  return _impl_.username_.Get();
}
inline void ChatPacket::_internal_set_username(const std::string& value) {
  
  _impl_.username_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatPacket::_internal_mutable_username() {
  
  return _impl_.username_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatPacket::release_username() {
  // @@protoc_insertion_point(field_release:chat.ChatPacket.username)
  return _impl_.username_.Release();
}
inline void ChatPacket::set_allocated_username(std::string* username) {
  if (username != nullptr) {
    
  } else {
    
  }
  _impl_.username_.SetAllocated(username, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.username_.IsDefault()) {
    _impl_.username_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.ChatPacket.username)
}

// string receiver = 4;
inline void ChatPacket::clear_receiver() {
  _impl_.receiver_.ClearToEmpty();
}
inline const std::string& ChatPacket::receiver() const {
  // @@protoc_insertion_point(field_get:chat.ChatPacket.receiver)
  return _internal_receiver();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatPacket::set_receiver(ArgT0&& arg0, ArgT... args) {
 
 _impl_.receiver_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.ChatPacket.receiver)
}
inline std::string* ChatPacket::mutable_receiver() {
  std::string* _s = _internal_mutable_receiver();
  // @@protoc_insertion_point(field_mutable:chat.ChatPacket.receiver)
  return _s;
}
inline const std::string& ChatPacket::_internal_receiver() const {
  return _impl_.receiver_.Get();
}
inline void ChatPacket::_internal_set_receiver(const std::string& value) {
  
  _impl_.receiver_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatPacket::_internal_mutable_receiver() {
  
  return _impl_.receiver_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatPacket::release_receiver() {
  // @@protoc_insertion_point(field_release:chat.ChatPacket.receiver)
  return _impl_.receiver_.Release();
}
inline void ChatPacket::set_allocated_receiver(std::string* receiver) {
  if (receiver != nullptr) {
    
  } else {
    
  }
  _impl_.receiver_.SetAllocated(receiver, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.receiver_.IsDefault()) {
    _impl_.receiver_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.ChatPacket.receiver)
}

// string group_id = 5;
inline void ChatPacket::clear_group_id() {
  _impl_.group_id_.ClearToEmpty();
}
inline const std::string& ChatPacket::group_id() const {
  // @@protoc_insertion_point(field_get:chat.ChatPacket.group_id)
  return _internal_group_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatPacket::set_group_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.group_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.ChatPacket.group_id)
}
inline std::string* ChatPacket::mutable_group_id() {
  std::string* _s = _internal_mutable_group_id();
  // @@protoc_insertion_point(field_mutable:chat.ChatPacket.group_id)
  return _s;
}
inline const std::string& ChatPacket::_internal_group_id() const {
  return _impl_.group_id_.Get();
}
inline void ChatPacket::_internal_set_group_id(const std::string& value) {
  
  _impl_.group_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatPacket::_internal_mutable_group_id() {
  
  return _impl_.group_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatPacket::release_group_id() {
  // @@protoc_insertion_point(field_release:chat.ChatPacket.group_id)
  return _impl_.group_id_.Release();
}
inline void ChatPacket::set_allocated_group_id(std::string* group_id) {
  if (group_id != nullptr) {
    
  } else {
    
  }
  _impl_.group_id_.SetAllocated(group_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.group_id_.IsDefault()) {
    _impl_.group_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.ChatPacket.group_id)
}

// string file_id = 6;
inline void ChatPacket::clear_file_id() {
  _impl_.file_id_.ClearToEmpty();
}
inline const std::string& ChatPacket::file_id() const {
  // @@protoc_insertion_point(field_get:chat.ChatPacket.file_id)
  return _internal_file_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatPacket::set_file_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.file_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.ChatPacket.file_id)
}
inline std::string* ChatPacket::mutable_file_id() {
  std::string* _s = _internal_mutable_file_id();
  // @@protoc_insertion_point(field_mutable:chat.ChatPacket.file_id)
  return _s;
}
inline const std::string& ChatPacket::_internal_file_id() const {
  return _impl_.file_id_.Get();
}
inline void ChatPacket::_internal_set_file_id(const std::string& value) {
  
  _impl_.file_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatPacket::_internal_mutable_file_id() {
  
  return _impl_.file_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatPacket::release_file_id() {
  // @@protoc_insertion_point(field_release:chat.ChatPacket.file_id)
  return _impl_.file_id_.Release();
}
inline void ChatPacket::set_allocated_file_id(std::string* file_id) {
  if (file_id != nullptr) {
    
  } else {
    
  }
  _impl_.file_id_.SetAllocated(file_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.file_id_.IsDefault()) {
    _impl_.file_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.ChatPacket.file_id)
}

// uint64 offset = 7;
inline void ChatPacket::clear_offset() {
  _impl_.offset_ = uint64_t{0u};
}
inline uint64_t ChatPacket::_internal_offset() const {
  return _impl_.offset_;
}
inline uint64_t ChatPacket::offset() const {
  // @@protoc_insertion_point(field_get:chat.ChatPacket.offset)
  return _internal_offset();
}
inline void ChatPacket::_internal_set_offset(uint64_t value) {
  
  _impl_.offset_ = value;
}
inline void ChatPacket::set_offset(uint64_t value) {
  _internal_set_offset(value);
  // @@protoc_insertion_point(field_set:chat.ChatPacket.offset)
}

// bytes payload = 8;
inline void ChatPacket::clear_payload() {
  _impl_.payload_.ClearToEmpty();
}
inline const std::string& ChatPacket::payload() const {
  // @@protoc_insertion_point(field_get:chat.ChatPacket.payload)
  return _internal_payload();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatPacket::set_payload(ArgT0&& arg0, ArgT... args) {
 
 _impl_.payload_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.ChatPacket.payload)
}
inline std::string* ChatPacket::mutable_payload() {
  std::string* _s = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:chat.ChatPacket.payload)
  return _s;
}
inline const std::string& ChatPacket::_internal_payload() const {
  return _impl_.payload_.Get();
}
inline void ChatPacket::_internal_set_payload(const std::string& value) {
  
  _impl_.payload_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatPacket::_internal_mutable_payload() {
  
  return _impl_.payload_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatPacket::release_payload() {
  // @@protoc_insertion_point(field_release:chat.ChatPacket.payload)
  return _impl_.payload_.Release();
}
inline void ChatPacket::set_allocated_payload(std::string* payload) {
  if (payload != nullptr) {
    
  } else {
    
  }
  _impl_.payload_.SetAllocated(payload, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.payload_.IsDefault()) {
    _impl_.payload_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.ChatPacket.payload)
}

// uint64 file_size = 9;
inline void ChatPacket::clear_file_size() {
  _impl_.file_size_ = uint64_t{0u};
}
inline uint64_t ChatPacket::_internal_file_size() const {
  return _impl_.file_size_;
}
inline uint64_t ChatPacket::file_size() const {
  // @@protoc_insertion_point(field_get:chat.ChatPacket.file_size)
  return _internal_file_size();
}
inline void ChatPacket::_internal_set_file_size(uint64_t value) {
  
  _impl_.file_size_ = value;
}
inline void ChatPacket::set_file_size(uint64_t value) {
  _internal_set_file_size(value);
  // @@protoc_insertion_point(field_set:chat.ChatPacket.file_size)
}

// string filename = 10;
inline void ChatPacket::clear_filename() {
  _impl_.filename_.ClearToEmpty();
}
inline const std::string& ChatPacket::filename() const {
  // @@protoc_insertion_point(field_get:chat.ChatPacket.filename)
  return _internal_filename();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatPacket::set_filename(ArgT0&& arg0, ArgT... args) {
 
 _impl_.filename_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.ChatPacket.filename)
}
inline std::string* ChatPacket::mutable_filename() {
  std::string* _s = _internal_mutable_filename();
  // @@protoc_insertion_point(field_mutable:chat.ChatPacket.filename)
  return _s;
}
inline const std::string& ChatPacket::_internal_filename() const {
  return _impl_.filename_.Get();
}
inline void ChatPacket::_internal_set_filename(const std::string& value) {
  
  _impl_.filename_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatPacket::_internal_mutable_filename() {
  
  return _impl_.filename_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatPacket::release_filename() {
  // @@protoc_insertion_point(field_release:chat.ChatPacket.filename)
  return _impl_.filename_.Release();
}
inline void ChatPacket::set_allocated_filename(std::string* filename) {
  if (filename != nullptr) {
    
  } else {
    
  }
  _impl_.filename_.SetAllocated(filename, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filename_.IsDefault()) {
    _impl_.filename_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.ChatPacket.filename)
}

// string password = 11;
inline void ChatPacket::clear_password() {
  _impl_.password_.ClearToEmpty();
}
inline const std::string& ChatPacket::password() const {
  // @@protoc_insertion_point(field_get:chat.ChatPacket.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatPacket::set_password(ArgT0&& arg0, ArgT... args) {
 
 _impl_.password_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.ChatPacket.password)
}
inline std::string* ChatPacket::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:chat.ChatPacket.password)
  return _s;
}
inline const std::string& ChatPacket::_internal_password() const {
  return _impl_.password_.Get();
}
inline void ChatPacket::_internal_set_password(const std::string& value) {
  
  _impl_.password_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatPacket::_internal_mutable_password() {
  
  return _impl_.password_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatPacket::release_password() {
  // @@protoc_insertion_point(field_release:chat.ChatPacket.password)
  return _impl_.password_.Release();
}
inline void ChatPacket::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  _impl_.password_.SetAllocated(password, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.ChatPacket.password)
}

// string message_id = 12;
inline void ChatPacket::clear_message_id() {
  _impl_.message_id_.ClearToEmpty();
}
inline const std::string& ChatPacket::message_id() const {
  // @@protoc_insertion_point(field_get:chat.ChatPacket.message_id)
  return _internal_message_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatPacket::set_message_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.ChatPacket.message_id)
}
inline std::string* ChatPacket::mutable_message_id() {
  std::string* _s = _internal_mutable_message_id();
  // @@protoc_insertion_point(field_mutable:chat.ChatPacket.message_id)
  return _s;
}
inline const std::string& ChatPacket::_internal_message_id() const {
  return _impl_.message_id_.Get();
}
inline void ChatPacket::_internal_set_message_id(const std::string& value) {
  
  _impl_.message_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatPacket::_internal_mutable_message_id() {
  
  return _impl_.message_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatPacket::release_message_id() {
  // @@protoc_insertion_point(field_release:chat.ChatPacket.message_id)
  return _impl_.message_id_.Release();
}
inline void ChatPacket::set_allocated_message_id(std::string* message_id) {
  if (message_id != nullptr) {
    
  } else {
    
  }
  _impl_.message_id_.SetAllocated(message_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_id_.IsDefault()) {
    _impl_.message_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.ChatPacket.message_id)
}

// int64 timestamp = 13;
inline void ChatPacket::clear_timestamp() {
  _impl_.timestamp_ = int64_t{0};
}
inline int64_t ChatPacket::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline int64_t ChatPacket::timestamp() const {
  // @@protoc_insertion_point(field_get:chat.ChatPacket.timestamp)
  return _internal_timestamp();
}
inline void ChatPacket::_internal_set_timestamp(int64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void ChatPacket::set_timestamp(int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:chat.ChatPacket.timestamp)
}

// int32 status = 14;
inline void ChatPacket::clear_status() {
  _impl_.status_ = 0;
}
inline int32_t ChatPacket::_internal_status() const {
  return _impl_.status_;
}
inline int32_t ChatPacket::status() const {
  // @@protoc_insertion_point(field_get:chat.ChatPacket.status)
  return _internal_status();
}
inline void ChatPacket::_internal_set_status(int32_t value) {
  
  _impl_.status_ = value;
}
inline void ChatPacket::set_status(int32_t value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:chat.ChatPacket.status)
}

// string status_message = 15;
inline void ChatPacket::clear_status_message() {
  _impl_.status_message_.ClearToEmpty();
}
inline const std::string& ChatPacket::status_message() const {
  // @@protoc_insertion_point(field_get:chat.ChatPacket.status_message)
  return _internal_status_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatPacket::set_status_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.status_message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.ChatPacket.status_message)
}
inline std::string* ChatPacket::mutable_status_message() {
  std::string* _s = _internal_mutable_status_message();
  // @@protoc_insertion_point(field_mutable:chat.ChatPacket.status_message)
  return _s;
}
inline const std::string& ChatPacket::_internal_status_message() const {
  return _impl_.status_message_.Get();
}
inline void ChatPacket::_internal_set_status_message(const std::string& value) {
  
  _impl_.status_message_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatPacket::_internal_mutable_status_message() {
  
  return _impl_.status_message_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatPacket::release_status_message() {
  // @@protoc_insertion_point(field_release:chat.ChatPacket.status_message)
  return _impl_.status_message_.Release();
}
inline void ChatPacket::set_allocated_status_message(std::string* status_message) {
  if (status_message != nullptr) {
    
  } else {
    
  }
  _impl_.status_message_.SetAllocated(status_message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.status_message_.IsDefault()) {
    _impl_.status_message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.ChatPacket.status_message)
}

// string extra = 16;
inline void ChatPacket::clear_extra() {
  _impl_.extra_.ClearToEmpty();
}
inline const std::string& ChatPacket::extra() const {
  // @@protoc_insertion_point(field_get:chat.ChatPacket.extra)
  return _internal_extra();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatPacket::set_extra(ArgT0&& arg0, ArgT... args) {
 
 _impl_.extra_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.ChatPacket.extra)
}
inline std::string* ChatPacket::mutable_extra() {
  std::string* _s = _internal_mutable_extra();
  // @@protoc_insertion_point(field_mutable:chat.ChatPacket.extra)
  return _s;
}
inline const std::string& ChatPacket::_internal_extra() const {
  return _impl_.extra_.Get();
}
inline void ChatPacket::_internal_set_extra(const std::string& value) {
  
  _impl_.extra_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatPacket::_internal_mutable_extra() {
  
  return _impl_.extra_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatPacket::release_extra() {
  // @@protoc_insertion_point(field_release:chat.ChatPacket.extra)
  return _impl_.extra_.Release();
}
inline void ChatPacket::set_allocated_extra(std::string* extra) {
  if (extra != nullptr) {
    
  } else {
    
  }
  _impl_.extra_.SetAllocated(extra, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.extra_.IsDefault()) {
    _impl_.extra_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.ChatPacket.extra)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace chat

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::chat::ChatPacket_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::chat::ChatPacket_Type>() {
  return ::chat::ChatPacket_Type_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_chat_2eproto
